### ISSUE TITLE
1-3 질문

### ISSUE THREAD

**Issue by dalzony** [eunmin/sicp#2]
나중엔 느려질 거 같아서, 혼자 조용히 풀고 있는데요. ㅋㅋ

다음과 같이 풀었는데, 혹시 `sort`라던가, `second` 함수같은 것도 직접 구현해보는게 좋겠죠?
너무 날로먹는거 아닌가 싶어서 질문 드립니다.

``` clojure
(def 문제
  "세 숫자를 인자로 받아 그 가운데 큰 숫자 두 개를 제곱한 다음,
그 두 값을 덧셈하여 내놓는 프로시저를 정의하라")

(defn square [x] (* x x))

(defn plus-max-two [x y z]
  (let [sorted-num (sort (list x y z))
        first (last sorted-num)
        second (second sorted-num)]
    (+ (square first) (square second))))

;;예
(plus-max-two 1 2 3)

```

**Comment by dalzony** [comment]
그러면 날로먹는 거라고 합니다. 자문 자답. ㅋㅋ 뿅

**Comment by eunmin** [comment]
그래도 코드리뷰를 드리면 
- `(list x y z)` 대신 `[x y z]`
  근거 : https://github.com/kwakbab/clojure-style-guide/blob/master/README-koKO.md#literal-col-syntax
- `first (last sorted-num) second ...` 대신 디스트럭처링 `(let [[f s] (reverse (sort [4 2 10]))] ...)`
- `first` `second` 대신 `f` , `s`도 괜찮을 것 같음

**Comment by dalzony** [comment]
@eunmin 아하 넵. 감사합니다 👍
