### ISSUE TITLE
clojure에서 나누기 궁금합니다.

### ISSUE THREAD

**Issue by amy-sesina** [eunmin/sicp#5]
문제풀때 average 함수를 만들면서 나누기를 사용하려고 했는데요..
3 나누기 2를 했더니 아래처럼 분수타입이 나왔어요.. ⚡ 

**sicp.amy.ex-1-6=> (/ 3 2)
3/2**

그래서 \* 1.0을 해서 소수타입으로 바꿔서 사용하긴 했는데요... 더 좋은 다른 방법이 있을 거 같은데 아시는 분 도와주세요~~

**(defn average "평균값 구한다" `[a b]`
  (\* (/ (+ a b) 2) 1.0))**

**Comment by dalzony** [comment]
@amy-sesina 
clojure에는  rational 타입이라는게 있는데요. 그게 저렇게 분수값으로 나오는 거에용.
따라서 연산에는 문제가 없는데요. 오히려 정확도가 있을 것 같습니다.
rational type을 소숫점으로 표현하고 싶으면 다음과 같은 방법들이 있습니다.

``` clojure
;; 피연산되는 숫자중 하나를 float 값으로 표현
;; 에이미처럼 1.0 곱하는 것과 비슷하겠네요.
(/ 3.0 2)
(/ 3 2.0)

;; double이나 float 함수로 캐스팅
(double (/ 3 2))
(float (/ 3 2))

```

1.6문제를 아직 풀지는 않았지만, 뉴튼 메소드가 나왔던 것 같은데요.
그러면 뭔가 반복해서 해당 연산을 하게 될거 같아서요.
따라서 평균값을 구하는 곳에는 `(/ (+ a b) 2)`을 사용하고

연산이 모두 끝나고 리턴 값에만 `(float 리턴값)`을 하면 될 것 같습니다.

**Comment by amy-sesina** [comment]
@dalzony 
문제풀면서 만든 함수 리턴값이 rational 타입으로 전달되니 이후 계산들이 다 분수가 되서 원하는 결과값이 안나오더라고요 ㅋㅋ
쥬니가 알려준 대로, float으로 전달하니 잘되네요~ 👍 

캄사합니다~ 이렇게 이슈는 컴플릿! 💯
